---
title: Abdul Aris
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    license: false
    aside:
      toc: true
    pageview: true
text_color_theme: sky
url: https://abdularis.com
baseurl: 
description: 'Developer notebook

'
lang: en
author:
  name: AbdulAris
  email: abdularisrahmanudin10@gmail.com
  facebook: sabdoel.sabdoel
  twitter: 
  github: abdularis
  linkedin: 
  googleplus: 
  weibo: 
  douban: 
repository: abdularis/abdularis.github.io
repository_tree: master
paths:
  base: "/"
excerpt_separator: "<!--more-->"
excerpt_type: html
toc:
  selectors: 
mathjax: 
mathjax_autoNumber: 
mermaid: 
chart: 
paginate: 8
paginate_path: "/page:num"
sources: unpkg
disqus:
  shortname: abdularis-com
gitalk:
  clientID: 
  clientSecret: 
  repository: 
  owner: 
  admin: 
leancloud:
  app_id: 
  app_key: 
  app_class: 
ga_tracking_id: UA-121096366-1
ga_anonymize_ip: false
markdown: kramdown
highlighter: rouge
permalink: date
exclude:
- CHANGELOG.md
- CHECKLIST.md
- Gemfile
- Gemfile.lock
- LICENSE
- README-*.md
- README.md
- gulpfile.js
- jekyll-text-theme.gemspec
- package-lock.json
- package.json
- "/docs"
- "/node_modules"
- "/screenshots"
- "/test"
- "/vendor"
plugins:
- jekyll-seo-tag
- jekyll-feed
- jekyll-paginate
- jekyll-sitemap
- jemoji
